// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddHistory(arg1:main.HistoryItem):Promise<void>;

export function AnalyzeAudio(arg1:string):Promise<Record<string, any>>;

export function CancelDownload():Promise<void>;

export function CheckSourceHealth(arg1:string):Promise<string>;

export function ClearHistory():Promise<void>;

export function ConfirmAmazonLogin():Promise<void>;

export function GetArtistDiscography(arg1:string):Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetDiscoveryData(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetDiscoveryGenres(arg1:string):Promise<string>;

export function GetDownloadedMusicLibrary():Promise<string>;

export function GetDownloadedRelease(arg1:string):Promise<string>;

export function GetHistory():Promise<Array<main.HistoryItem>>;

export function GetSlskdWebUIInfo():Promise<string>;

export function GetSpotifyPlaylists():Promise<string>;

export function GetSpotifyStatus():Promise<string>;

export function GetSupportStatus():Promise<string>;

export function LoginSpotify():Promise<string>;

export function LogoutSpotify():Promise<string>;

export function PickAnalyzerFiles():Promise<Array<string>>;

export function PickDirectory():Promise<string>;

export function RequestAccessKey():Promise<main.KeyGenResult>;

export function RetryTrackDownload(arg1:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function ScanFolder(arg1:string):Promise<Array<string>>;

export function SearchArtists(arg1:string,arg2:string):Promise<string>;

export function SetSpotifyCookie(arg1:string):Promise<string>;

export function SetSpotifyToken(arg1:string):Promise<string>;

export function StartAmazonBrowserLogin():Promise<void>;

export function StartAppleBrowserLogin():Promise<void>;

export function StartDownload(arg1:Array<string>):Promise<void>;

export function StartTidalOAuthLogin():Promise<void>;

export function ValidateTidalAuth():Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
