// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistory(arg1) {
  return window['go']['main']['App']['AddHistory'](arg1);
}

export function AnalyzeAudio(arg1) {
  return window['go']['main']['App']['AnalyzeAudio'](arg1);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CheckSourceHealth(arg1) {
  return window['go']['main']['App']['CheckSourceHealth'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ConfirmAmazonLogin() {
  return window['go']['main']['App']['ConfirmAmazonLogin']();
}

export function GetArtistDiscography(arg1) {
  return window['go']['main']['App']['GetArtistDiscography'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiscoveryData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDiscoveryData'](arg1, arg2, arg3);
}

export function GetDiscoveryGenres(arg1) {
  return window['go']['main']['App']['GetDiscoveryGenres'](arg1);
}

export function GetDownloadedMusicLibrary() {
  return window['go']['main']['App']['GetDownloadedMusicLibrary']();
}

export function GetDownloadedRelease(arg1) {
  return window['go']['main']['App']['GetDownloadedRelease'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetSlskdWebUIInfo() {
  return window['go']['main']['App']['GetSlskdWebUIInfo']();
}

export function GetSpotifyPlaylists() {
  return window['go']['main']['App']['GetSpotifyPlaylists']();
}

export function GetSpotifyStatus() {
  return window['go']['main']['App']['GetSpotifyStatus']();
}

export function GetSupportStatus() {
  return window['go']['main']['App']['GetSupportStatus']();
}

export function LoginSpotify() {
  return window['go']['main']['App']['LoginSpotify']();
}

export function LogoutSpotify() {
  return window['go']['main']['App']['LogoutSpotify']();
}

export function PickAnalyzerFiles() {
  return window['go']['main']['App']['PickAnalyzerFiles']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function RequestAccessKey() {
  return window['go']['main']['App']['RequestAccessKey']();
}

export function RetryTrackDownload(arg1) {
  return window['go']['main']['App']['RetryTrackDownload'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function SearchArtists(arg1, arg2) {
  return window['go']['main']['App']['SearchArtists'](arg1, arg2);
}

export function SetSpotifyCookie(arg1) {
  return window['go']['main']['App']['SetSpotifyCookie'](arg1);
}

export function SetSpotifyToken(arg1) {
  return window['go']['main']['App']['SetSpotifyToken'](arg1);
}

export function StartAmazonBrowserLogin() {
  return window['go']['main']['App']['StartAmazonBrowserLogin']();
}

export function StartAppleBrowserLogin() {
  return window['go']['main']['App']['StartAppleBrowserLogin']();
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function StartTidalOAuthLogin() {
  return window['go']['main']['App']['StartTidalOAuthLogin']();
}

export function ValidateTidalAuth() {
  return window['go']['main']['App']['ValidateTidalAuth']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
